"""IR-SQL/PGQ — representación intermedia tipada.

Re-exporta los nodos y las funciones top-level de ``lift`` y ``compile`` para
que el resto del proyecto consuma la API estable desde ``core.ir``.
"""

from .compile import compile_query
from .lift import lift_sql
from .nodes import (
    Aggregate,
    BetweenExpr,
    BinaryOp,
    CaseExpr,
    CastExpr,
    ColumnExpr,
    ColumnRef,
    EdgePattern,
    ExistsExpr,
    Expression,
    FromExpr,
    FromGraphMatch,
    FromSubquery,
    FromTable,
    FunctionCall,
    GraphQuery,
    InExpr,
    IsNullExpr,
    Join,
    LikeExpr,
    Literal,
    MatchPattern,
    OrderItem,
    ParenExpr,
    PathPattern,
    Query,
    RelationalQuery,
    SelectItem,
    SetOperation,
    Star,
    Subquery,
    TableRef,
    UnaryOp,
    VertexPattern,
)

__all__ = [
    "Aggregate",
    "BetweenExpr",
    "BinaryOp",
    "CaseExpr",
    "CastExpr",
    "ColumnExpr",
    "ColumnRef",
    "EdgePattern",
    "ExistsExpr",
    "Expression",
    "FromExpr",
    "FromGraphMatch",
    "FromSubquery",
    "FromTable",
    "FunctionCall",
    "GraphQuery",
    "InExpr",
    "IsNullExpr",
    "Join",
    "LikeExpr",
    "Literal",
    "MatchPattern",
    "OrderItem",
    "ParenExpr",
    "PathPattern",
    "Query",
    "RelationalQuery",
    "SelectItem",
    "SetOperation",
    "Star",
    "Subquery",
    "TableRef",
    "UnaryOp",
    "VertexPattern",
    "compile_query",
    "lift_sql",
]
